### ISSUE TITLE
fortran build no longer works

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#12]
Looks like the arg changes related to error handling refactor broke the fortran compat code:
```
src/szf.c: In function 'sz_batch_decompress_c_':
src/szf.c:514:2: error: too few arguments to function 'SZ_batch_decompress'
  SZ_batch_decompress(bytes, *byteLength);
  ^~~~~~~~~~~~~~~~~~~
In file included from src/szf.c:14:0:
./include/sz.h:421:12: note: declared here
 SZ_VarSet* SZ_batch_decompress(unsigned char* compressedStream, int length, int *status);
```

**Comment by disheng222** [comment]
Hi Bryce.
Oh. Yes.
I changed the C interface of SZ_batch_decompress() to be SZ_VarSet*
SZ_batch_decompress(unsigned char* compressedStream, int compressedLength,
int *status), but I didn't change the corresponding Fortran code.
I can fix it asap (in a couple of days), because I am super busy these day.
Is that ok?
Thanks.

Best,
Sheng

2017-02-27 15:05 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by bd4** [comment]
I think a couple of days will be fine, @jychoi-hpc does ADIOS need SZ with `--enable-fortran`?

**Comment by jychoi-hpc** [comment]
No. SZ C binding is enough for Adios.

Thank you for checking.

Jong

**Comment by disheng222** [comment]
Hi Bryce,
I have fixed the problem about fortran interface related to batch
compression.
You can find a new example code called testdouble_batch_f.f90.
It can only work in the Fortran mode compilation, i.e., ./configure ....
--enable-fortran

The version is 1.4.9.1

Best,
Sheng

2017-02-28 9:30 GMT-06:00 Jong Choi <notifications@github.com>:
