### ISSUE TITLE
new feature: timing trace file

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#13]
For analyzing the cost of adding compression to real science applications, we'd like to have a way of logging the time it takes for each compress and decompress operations. I'm thinking of a library level function that sets the log file:

SZ_set_timing_log_file(char *path)

And if this is set, each compress/decompress routine saves the time at start, and logs a single line with the duration. Making it thread safe would require some locking.

Is this something you would be interested in adding or accept as a pull request?

**Comment by disheng222** [comment]
Hi Bryce,
Thanks.
This interface looks fine to me.
In the example/ directory, you can find that I used cost_start() and
cost_end() to check and calculate the time. In fact, I can put them in the
SZ library if users want to call it directlry by linking there.

What do you mean by "char *path"? The log file?


2017-04-11 11:58 GMT-05:00 Bryce Allen <notifications@github.com>:

**Comment by bd4** [comment]
Re path, I do mean the path to the log file, `char *log_file_path` would be a better name.

I was thinking to directly instrument each compress/decompress with timing, conditioned on whether the log file is set. This is way easier than instrumenting each app that calls SZ.

**Comment by disheng222** [comment]
Hi Bryce,
I see. If you want to do that, just go ahead, as long as the logging
function is optional for users (they can switch it on/off by modifying the
configuration file or so).
Thanks.

Best,
Sheng

2017-04-12 10:55 GMT-05:00 Bryce Allen <notifications@github.com>:

**Comment by bd4** [comment]
Great thanks, I will work on it and submit a pull request when it's ready.

**Comment by bd4** [comment]
It looks like SZ_compress/decompress and the _args versions are all thread safe - the only shared library global data is read only config. The batch compress/decompress routines on the other hand use a shared list of vars, so they are not thread safe. Is this correct? Trying to decide if it's worth adding locking to the performance logging or not.

**Comment by disheng222** [comment]
Hi Bryce,
Yes. As for multi-thread implementation for SZ, the only thing to care
about is the "global" variables and memory.
I think all global variables are listed in sz.h and Huffman.h.
The variables in sz.h are easy to handle, because they are just parameters.
The ones in Huffman.h are related to Huffman tree.
In the compression, SZ needs to create a Huffman tree based on the maximum
number of quantization intervals configured by users (e.g., set in the
configure file), as shown below.

extern struct node_t* pool;
extern node *qqq, *qq;
extern int n_nodes, qend; //n_nodes is for compression
extern unsigned long **code;
extern unsigned char *cout;
extern int n_inode; //n_inode is for decompression

The Huffman tree will be recreated during the decompression based on the
"compressed" data.

In principle, for different variables or different data sets, Huffman tree
memory should be separate.

2017-04-18 16:59 GMT-05:00 Bryce Allen <notifications@github.com>:

**Comment by bd4** [comment]
After further discussion we've decided that ADIOS would be a more appropriate place to add a compression timing, so we can support multiple compression algorithms with common timing code. The idea with adding it to SZ was to have a stopgap until it gets added to ADIOS, but it looks like we can wait. Closing this for now.
