### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by kshitij-v-mehta** [disheng222/SZ#15]
Various compilation errors of the type:

```src/szf.c:35:6: error: conflicting types for 'sz_compress_d1_float_'
 void sz_compress_d1_float_(float* data, unsigned char *bytes, size_t *outSize, int *r1) 
      ^
In file included from ./include/sz.h:28:0,
                 from src/szf.c:14:
./include/szf.h:23:6: note: previous declaration of 'sz_compress_d1_float_' was here
```

The function signature in the .c and .h files does not match.

Testing with gcc 4.9.3 on Titan.

**Comment by disheng222** [comment]
Hi, 
The issue has been fixed. 
I guess you are trying to compile and run the Fortran interface of SZ. 
Previously, some bugs were introduced when changing the size type from "int" to "size_t". 
It should work fine now.

**Comment by kshitij-v-mehta** [comment]
Thanks,
Compilation still fails.

```
testdouble_batch_f.f90:36.38:

        call SZ_Batch_Compress(Bytes, outSize)
                                      1
Error: Type mismatch in argument 'outsize' at (1); passed INTEGER(4) to INTEGER(8)
testdouble_batch_f.f90:37.54:

        call writeData(Bytes, outSize, 'test12_f.sz') 
                                                      1
Error: There is no specific subroutine for the generic 'writedata' at (1)
testdouble_batch_f.f90:43.40:

        call SZ_Batch_Decompress(Bytes, outSize, ierr)
                                        1
Error: Type mismatch in argument 'outsize' at (1); passed INTEGER(4) to INTEGER(8)
testdouble_batch_f.f90:44.41:

        call SZ_GetVarDim('grid1', dim_, g1, g2, g3, g4, g5)
                                         1
Error: Type mismatch in argument 'r1' at (1); passed INTEGER(4) to INTEGER(8)
```

**Comment by jychoi-hpc** [comment]
I have just checked out the master branch and tried. I got the same error with "--enable-fortran" option.

**Comment by disheng222** [comment]
Hi,
Thanks for the report.
The reason is that the new release of SZ (including Fortran version)
supports size_t to denote the size of data instead of integer type.
I forgot to update the example codes to make it consistent with the change.
I changed the definition of the size to be INTEGER(kind=C_SIZE_T).
For example:
 integer(kind=C_SIZE_T) :: gridsize1,gridsize2,gridsize3

Then, the problem is gone.

For testing Fortran version, you can run the following commands in the
example/ directory:
./testdouble_compress_f sz.config
./testdouble_decompress_f sz.config

Please feel free to let me know if you encounter any more issues.

Best,
Sheng

2017-09-03 12:48 GMT-05:00 Jong Choi <notifications@github.com>:
