### ISSUE TITLE
cmake: headers are not installed

### ISSUE THREAD

**Issue by jschueller** [disheng222/SZ#34]
with cmake, sz.h headers and friends are not installed
note that dictionary.h and iniparser.h must not be included as they are part of iniparser

also, probably test executable dont need to be installed

**Comment by disheng222** [comment]
Done. The headers will be copied to installation dir. The test executables (such as testfloat_compress and testfloat_decompress) are stilled installed, because they are mentioned in user-guide as examples about how to call SZ API from user codes. FYI, iniparser is in MIT license, so no problem to put it in the package. I kept their headers unchanged to claim their contributions.
