### ISSUE TITLE
About random access or random decompression

### ISSUE THREAD

**Issue by gu7ue** [disheng222/SZ#53]
I am curious whether the random decompression function is already available. I found the function "SZ_decompress_args_randomaccess_float()" which is in the file "sz_randomaccess.c" is only declared, but without implementing.

**Comment by disheng222** [comment]
Random decompression is available.
In order to enable it, you need to add "--enable-randomaccess" when running
./configure command during the installation. Then, make & make install.
In the source code, please search for the key word "HAVE_RANDOMACCESS" to
find the related functions. For example, in sz_float.c, you will find the
following lines:
#ifdef HAVE_RANDOMACCESS
}
else
tmpByteData =
SZ_compress_float_3D_MDQ_decompression_random_access_with_blocked_regression(oriData,
r3, r2, r1, realPrecision, &tmpOutSize);
#endif

This is the compression function supporting random access decompression.

I attached a tech. report for your further interest.

Best,
Sheng
