### ISSUE TITLE
Decompressed data becomes half length

### ISSUE THREAD

**Issue by kaushil24** [disheng222/SZ#54]
I am converting a 1-D array (len = 40485) . Here is the code: 
```
print(arr.shape) 
# (40485, )
np.savetxt('output.dat', arr)
```
Then running the following commands for compression and decompression
```
sz -z -f -i output.dat -1 48045
sz -x -f -s output.dat.sz -1 48045
```

Reading the decompressed file in numpy gives the following results
```
output_arr = np.fromfile('output.dat.sz.out')
print(f'Before compression shape {arr.shape} | After compression shape {output_arr.shape}')
# Before compression shape (48045, ) | After compression shape (24022, )
```
How can I retrieve back the original size array ?

**Comment by disheng222** [comment]
Could you send me the data file (disheng222@gmail.com)?
Thanks.

**Comment by disheng222** [comment]
BTW, SZ is not designed for compressing such a small data file (only
200KB), because SZ has a constant overhead in maintaining the Huffman tree.
If you still need to compress the small data files like that, I suggest you
to set the max quantization intervals to a small number in sz.config:
max_quant_intervals = 65536 --> max_quant_intervals = 16
or max_quant_intervals = 4.
Then, run the command like:
sz -z -f -i output.dat -1 48045 -c sz.config
(What error bound did you use? In general, you need to use -M and -A/-R to
give the error bound information)

Best,
Sheng

**Comment by kaushil24** [comment]
Thank you for responding. 

> SZ is not designed for compressing such a small data file (only
200KB)

The file size is 1.2 MB. Do  I still need to change sz.config.

> What error bound did you use? In general, you need to use -M and -A/-R to
give the error bound information

I did not set error bound. Used the default. 

Also, I have mailed you the file.

**Comment by disheng222** [comment]
Hi Kaushil, 
I noted that the file you are using is a text file. 
Please note that the input data file should be a binary file.
After converting your txt file to binary file, then everything looks good.
[sdi@sdihost test]$ sz -z -f -i ecg_sz.f32 -M ABS -A 1E-3 -1 48045
opt_quantizations=256, exactDataNum=145, sum=145
compression time = 0.004962
compressed data file: ecg_sz.f32.sz
[sdi@sdihost test]$ sz -x -f -i ecg_sz.f32 -1 48045 -s ecg_sz.f32.sz -a
Min=-1.2730000019073486328, Max=2.0499999523162841797, range=3.3229999542236328125
Max absolute error = 0.0009999871
Max relative error = 0.000301
Max pw relative error = 0.999548
PSNR = 73.820993, NRMSE= 0.00020368092553574285554
normError = 0.148356, normErr_norm = 0.002646
acEff=0.999997
compressionRatio=6.055393
decompression time = 0.010504 seconds.
decompressed data file: ecg_sz.f32.sz.out
[sdi@sdihost test]$ 

-M ABS means using absolute error bound mode. 
-A means the error bound is set to 1E-3. 

Best,
Sheng
